
name: Build CDR Photo Match Pro

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-2022

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v2

      - name: Restore packages
        run: nuget restore CDRPhotoMatchPro.csproj -PackagesDirectory packages
      - name: Force install SQLite
        run: nuget install System.Data.SQLite.Core -Version 1.0.118.0 -OutputDirectory packages
      - name: Build Debug
        run: msbuild CDRPhotoMatchPro.csproj /p:Configuration=Debug /p:Platform="AnyCPU"
      - name: Find netstandard DLL
        run: Get-ChildItem -Path C:\ -Filter netstandard.dll -Recurse -ErrorAction SilentlyContinue | Select-Object FullName

               
      - name: Upload build output
        uses: actions/upload-artifact@v4
        with:
          name: CDRPhotoMatchPro-Debug
          path: bin/Debug/**
